import "@/app/_style/globals.css";
import { Josefin_Sans } from "next/font/google";
import Header from "./_components/Header";

const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "인터뷰닷",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${josefin.className} antialiased 
         text-primary-950  min-h-screen flex flex-col relative`}
      >
        <Header />

        <div className="flex-1 px-8 py-12 bg-gray-100">
          <main className="max-w-7xl mx-auto w-full">{children}</main>
        </div>
        <footer>Copyright by ... </footer>
      </body>
    </html>
  );
}
